const Globals = {
	USER_LOG_IN : "userLogIn",
	CHECK_USER_LOG_IN : "checkUserLogIn",
	GET_SECTION : 'getSection',
	INITIAL_DOWNLOAD_FILE : 'initialDownloadFile',
	USER_REGISTERED : "userRegistered",
	USER_REGISTRATION : "userRegistration",
	ON_CONFIRMATION_FILE : "onConfirmationFile",
	SHOW_ERROR : "showError",
	ON_CONFIRM_FORM : "onConfirmForm",
	ON_CONFIRM_DOWNLOAD : "onConfirmDownload",
	ON_CONFIRMATION_USER_REGISTERED : "onConfirmationUserRegistered",
	ON_CONFIRMATION_USER_REGISTRATION : "onConfirmationUserRegistration",
	THANKS_FOR_THE_DOWNLOAD : "thanksForTheDownload",
	DOWNLOAD_FILE : "downloadFile",
	CLOSE_POPUP : "closePopup",
	MESSAGE_FORM_INVALID_EMAIL : "Email no válido",
	MESSAGE_FORM_NOT_AVAILABLE_EMAIL : "Email no disponible",
	MESSAGE_FORM_NOT_AVAILABLE_USER : "Usuario no registrado",
	MESSAGE_FORM_INVALID_NAME : "Debes completar el nombre",
	MESSAGE_FORM_INVALID_LAST_NAME : "Debes completar el apellido",
	MESSAGE_FORM_INVALID_SCHOOL : "Debes completar la escuela",
	MESSAGE_FORM_INVALID_ADDRESS : "Debes completar la dirección",
	MESSAGE_FORM_INVALID_CITY : "Debes completar la ciudad",
	MESSAGE_FORM_INVALID_SUBJECT : "Debes completar la materia",
	MESSAGE_FILE_IN_DATABASE : "No existe el archivo cargado en la Base de datos",
	MESSAGE_NOT_EXIST : "Archivo inexistente",
	MESSAGE_FILE_EXIST : "Existe el archivo",
	TIME_USER_CONFIRMATION_VIEW : 2,
	TIME_THANKS_FOR_THE_DOWNLOAD : 2,
	TIME_TO_SHOW_FORM_ERROR : 2
};